package crudoperation;

import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

public class ShowProduct extends javax.swing.JFrame {

     public final static String DB_NAME = "jdbc_crud";
    public final static String DB_USER = "Nischal";
    public final static String DB_PASS = "Nischal@123";
    public final static String DB_URL = "jdbc:mysql://localhost:3306/"+DB_NAME;
    public static Connection CONN;
    public static Statement STMT;
    public int product_id = 0;

    public ShowProduct() {
        initComponents();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            CONN = DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
            STMT = CONN.createStatement();
          
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_show = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_view = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_products = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DAV Product List");

        btn_show.setText("Show");
        btn_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showActionPerformed(evt);
            }
        });

        btn_add.setText("Add New");

        btn_view.setText("View");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        tbl_products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SNO", "TITLE", "DESC", "CATEGORY", "QUANTITY", "PRICE"
            }
        ));
        jScrollPane1.setViewportView(tbl_products);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_show)
                        .addGap(52, 52, 52)
                        .addComponent(btn_add)
                        .addGap(43, 43, 43)
                        .addComponent(btn_view)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_edit)
                        .addGap(15, 15, 15))))
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_show)
                    .addComponent(btn_add)
                    .addComponent(btn_view)
                    .addComponent(btn_edit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showActionPerformed
            // TODO add your handling code here:
            
            try{
                String sql = "Select * from products";
                ResultSet rs = STMT.executeQuery(sql);
                
                int counter = 1; 
                DefaultTableModel model = (DefaultTableModel) tbl_products.getModel();
                while(rs.next()){
                    int product_id = rs.getInt("product_id");
                    String title = rs.getString("title");
                    String category = rs.getString("category");
                    String desc = rs.getString("description");
                    int quantity = rs.getInt("quantity");
                    double price = rs.getDouble("price");
                    
                    Object data[] = {counter,title,category,desc,price,quantity};
                    model.addRow(data);
                    counter++;
                }
            }catch(Exception e){
                System.out.println("Message:"+e.getMessage());
            }
    }//GEN-LAST:event_btn_showActionPerformed

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        // TODO add your handling code here:
        int row_no = tbl_products.getSelectedRow();
        if(this.product_id <=0&& row_no<0){
            JOptionPane.showMessageDialog(rootPane, "pleasse Select Product");
        }else{
            this.product_id = Integer.parseInt(tbl_products.getModel().getValueAt(row_no, 0).toString());
            String sql = "SElECT * from products where product_id = "+product_id;
            try{
                STMT = CONN.createStatement();
                ShowProductList sp = new ShowProductList();
                ResultSet rs = STMT.executeQuery(sql);
                sp.setVisible(true);
                
                sp.showProductDetails(rs);
                
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Message" + e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_viewActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        int row_no = tbl_products.getSelectedRow();
        if(this.product_id <=0 && row_no<0){
            JOptionPane.showMessageDialog(rootPane, "Please Select the produc");
        }else{
            this.product_id = Integer.parseInt(tbl_products.getModel().getValueAt(row_no, 1).toString());
            String sql = "SELECT * FROM product WHERE product_id="+ this.product_id;
            try{
                ResultSet rs = STMT.executeQuery(sql);
                EditProduct ep = new EditProduct();
                ep.setVisible(true);
                ep.EditProductDetails(rs,this.CONN);
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_btn_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_show;
    private javax.swing.JButton btn_view;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_products;
    // End of variables declaration//GEN-END:variables
}
